### ISSUE TITLE
Adjust LIght/Dark mode to System Settings

### ISSUE THREAD

**Issue by akyriako** [opentelekomcloud/docs-next#133]

**Comment by akyriako** [comment]
@SebastianGode there is flashing light effect when (re)loading the dark theme

**Comment by SebastianGode** [comment]
@akyriako This is only the case if the selected color scheme is different than the default of the users system.
For example if your smartphone or PC is in dark mode and you have the website in dark mode as well all is fine. For the case that you have the system set to light mode but want the website in dark mode you have the short flashing.

This is caused by Telekom Scale because Scale doesn't use local storage for saving the selected theme and only changes that on initial load of the page each time. I can try to find a solution to that, but I'm not 100% confident that I find one.
